AWSTemplateFormatVersion: '2010-09-09'
Description: 'Passenger Permission Set for Airline Identity Risk Lab'

Parameters:
  SSOInstanceArn:
    Type: String
    Description: 'AWS IAM Identity Center Instance ARN'

Resources:
  PassengerPermissionSet:
    Type: 'AWS::SSO::PermissionSet'
    Properties:
      Name: 'PassengerPermissionSet'
      Description: 'Read-only passenger API access (airline demo)'
      InstanceArn: !Ref SSOInstanceArn
      SessionDuration: 'PT1H'
      RelayState: 'https://api.airline.example.com'
      InlinePolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowPassengerReadAPI'
            Effect: Allow
            Action:
              - execute-api:Invoke
            Resource:
              - !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/GET/passengers/*'
              - !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/GET/flights/*'
